### PR TITLE
Auto deploy

### PR DESCRIPTION
**Pull request by zigomir**
This auto deploy already works with [now](https://zeit.co/docs/integrations/now-for-github) when I use a fork of `stateless-components` under my account. 

I requested Celtra GitHub organization for permission – @jakajancar can you please approve it? It should only have access to this `stateless-components` repository.

Fixes https://github.com/celtra/stateless-components/issues/72

### CODE REVIEW

**Comment by jakajancar** [comment]
@zigomir
Can you explain a bit more how the now deployment works? Where is it deploying to? Do we have an account there (who owns it?) or is it free? If we approve the app for the org, I assume anyone can then also add it to e.g. `celtra/mab`? ...

//cc @celtra/devops

**Comment by deanrock** [comment]
@zigomir Why do we need/want to use now? Can we achieve similar thing with CircleCI which is established solution for other projects?

Also, why do we trust/prefer `mhart/alpine-node` Docker image, instead of the official `node:whatever`?

**Comment by jakajancar** [comment]
I would really prefer if we just use Circle like for other projects. Otherwise we can use now as well, but please work with DevOps to sign up for a paid now account owned by Celtra. We need some binding ToS at least. Even if this project is not sensitive/public (not sure if this is intentional), one will eventually be, and I can only approve this at org level.

**Comment by zigomir** [comment]
@zan-kusterle I see we now have http://components.celtra.com, cool! (just heard from @3buson on dev-meeting) and looks like we're building this with docker. Do we have auto deploys?

I'd also add http://components.celtra.com url to README ;)

**Pull request closed without merging**
