### PR TITLE
New design: only active state

### PR DESCRIPTION
**Pull request by zigomir**
Part of https://celtra.atlassian.net/browse/MAB-13049

@kurent please take a look. This is coming from new designs: https://celtra.invisionapp.com/d/main#/console/14770118/307122294/inspect

I sure hope same will be used for report generator, otherwise please let me know so we can talk with Andrej V.

I couldn't get colors for close button with Invision Inspect mode, so this part is still missing. Do you usually get sketch files from designers? I first wanted to see if I can download sketch file from Invision but wasn't successful with that.

If you do have a sketch file, can you please take care of close button colors?

[edit] I have a sketch file and I added close button colors. Will put this in product review.

Dark theme: https://dist-weqfxrmdly.now.sh/#/
Light theme: https://dist-nqliplarww.now.sh/#/

### CODE REVIEW

**Comment by zigomir** [comment]
@kurent this is going into product review now. Please confirm that you're using same chip design on your side (Report Generator?) and if so, I'll merge this into `filter-chip` once product confirms it. We can do CR fixes in `filter-chip` branch imo.

**Comment by kurent** [comment]
yes, this is not in sync with what I had in specs, but I'll check with @andrejventa to see if that changed.  The changes made are not that huge, I guess this can be used in Report builder too. The main difference is active state, which, in my case, was @royal-blue color. If that is gone, we can simplify this component quite a bit, as you did already. 

Again, I'll check with Venta today, and let you know.

**Comment by andrejventa** [comment]
@kurent @zigomir Yes, please use the simplified chip design you see on [invision](https://celtra.invisionapp.com/d/main#/console/14770118/307122294/preview). [sketch file here](https://www.dropbox.com/s/mmzv5jcmqwll33v/filters.sketch?dl=0). 

Ziga please nota a small change added just now - the close button (X) has now .6 opacity on all states (dark & light) and 1 on hover.

**Comment by zigomir** [comment]
I got confirmation that this design is OK by @andrejventa and @ashnakothari87. Merging it now back to `filter-chip` branch. /cc @kurent

**Comment by kurent** [comment]
👍

**Pull request merged**
